// Automatically generated by SUtools, editing not advised.
#ifndef R_SPARSENET_H
#define R_SPARSENET_H
#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>
#ifdef ENABLE_NLS
#include <libintl.h>
#define _(String) dgettext ("sparsenet", String)
#else
#define _(String) (String)
#endif

#define FDEF(name)  {#name, (DL_FUNC) &F77_SUB(name), sizeof(name ## _t)/sizeof(name ## _t[0]), name ##_t}
void F77_SUB(sparsenet)(
int *no,
int *ni,
double *x,
double *y,
double *w,
int *jd,
int *ne,
int *nx,
int *ngam,
int *nlam,
double *fxgam,
double *flmin,
double *par,
int *igrid,
int *istart,
double *thr,
int *maxit,
int *lmu,
double *a0,
double *ca,
int *ia,
int *nin,
double *rsq,
int *nlp,
int *jerr
);
 
static R_NativePrimitiveArgType sparsenet_t[] = {
INTSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP,
INTSXP,
INTSXP,
INTSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP,
INTSXP,
INTSXP,
REALSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP,
INTSXP,
REALSXP,
INTSXP,
INTSXP
};

static R_FortranMethodDef fMethods[] = {
FDEF(sparsenet) ,
{NULL, NULL, 0}
};

void R_init_sparsenet(DllInfo *dll){
  R_registerRoutines(dll, NULL, NULL, fMethods, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
#endif
